# frontend/Dockerfile
FROM node:22 AS build

WORKDIR /app

COPY ./frontend/admin-dashboard ./
RUN export NODE_OPTIONS=--openssl-legacy-provider
RUN npm install

EXPOSE 3000
CMD ["npm", "run", "start"]